"""Organisation / clipper seed for the 274 creators (Stage 0).

This is the *seed* that pipeline_titles.creators writes to data/titles/analysis/creators.csv
for hand correction; every later stage reads creators.csv, never this file, so corrections
only need to be made in the CSV. Assignments were made from the channel names and channel
descriptions (2026-09-14).

Entry: creator -> (organisation, clipper, note). organisation groups sister channels of one
outlet (used to drop same-outlet cross-posts from every similarity calculation and for the
organisation-level style table); clipper marks channels whose titles are written by fans
or an editing team rather than the creator, kept as their own group so a fan editor's style
is never attributed to the creator. The note is a short description of the channel (format,
country, network); the channel's political grouping is never assumed here, it comes from the
leaning stage.
"""

CREATORS = {
    # ---- caption-corpus creators ----
    "@AsmonTV": ("Asmongold", True, "run by Daily Dose of Asmongold / CatDany per description; gaming + politics reaction"),
    "@BenShapiro": ("Daily Wire", False, ""),
    "@ClipsCandaceOwens": ("Candace Owens", True, "official clips channel"),
    "@HasanAbi": ("HasanAbi", False, ""),
    "@HasanAbiVODs3": ("HasanAbi", True, "official VOD channel; date-stamped titles written by the VOD team"),
    "@LukeBeasley": ("Luke Beasley", False, ""),
    "@MattWalsh": ("Daily Wire", False, ""),
    "@MegynKelly": ("Megyn Kelly", False, "interview-heavy show; titles are news commentary"),
    "@MeidasTouch": ("MeidasTouch Network", False, "self-described news network; titles are commentary"),
    "@MichaelKnowles": ("Daily Wire", False, ""),
    "@PBDPodcast": ("Valuetainment", False, ""),
    "@PartOfTheProblem": ("Dave Smith", False, "anti-war"),
    "@SecularTalk": ("Kyle Kulinski", False, ""),
    "@StevenCrowder": ("Louder with Crowder", False, ""),
    "@TheMajorityReport": ("Majority Report", False, ""),
    "@TheYoungTurks": ("TYT Network", False, "cross-posts with The Damage Report"),
    "@TimDillonShow": ("Tim Dillon", False, "comedian podcast"),
    "@Timcast": ("Timcast", False, ""),
    "@TuckerCarlson": ("Tucker Carlson Network", False, "mostly long-form interviews"),
    "@Vaush": ("Vaush", False, ""),
    "@adammockler": ("Adam Mockler", False, ""),
    "@bennyjohnson": ("Benny Johnson", False, "TPUSA contributor"),
    "@breakingpoints": ("Breaking Points", False, ""),
    "@briantylercohen": ("Brian Tyler Cohen", False, ""),
    "@deanwithrs": ("Dean Withers", False, "debate streamer"),
    "@destiny": ("Destiny", False, ""),
    "@glennbeck": ("Blaze Media", False, ""),
    "@hutch": ("Hutch", False, ""),
    "@joerogan": ("Joe Rogan", False, ""),
    "@podsaveamerica": ("Crooked Media", False, ""),
    "@ponderingpolitics": ("Pondering Politics", False, ""),
    "@samharrisorg": ("Sam Harris", False, ""),
    "@thedavidpakmanshow": ("David Pakman", False, ""),
    # ---- YouTube, rest of the list ----
    "@triggerpod": ("Triggernometry", False, ""),
    "@MLChristiansen": ("Matt Christiansen", False, ""),
    "@TheOfficerTatum": ("Officer Tatum", False, ""),
    "@therationalnational": ("Rational National", False, "Canadian"),
    "@SecondThought": ("Second Thought", False, "explainer videos"),
    "@bulwarkmedia": ("The Bulwark", False, ""),
    "@LeejaMiller": ("Leeja Miller", False, "lawyer explainer"),
    "@PiersMorganUncensored": ("Piers Morgan", False, "debate / interview show"),
    "@zeteo": ("Zeteo", False, ""),
    "@TheDamageReport": ("TYT Network", False, "cross-posts with TYT"),
    "@TheHumanistReport": ("Humanist Report", False, ""),
    "@FarronBalanced": ("Farron Balanced", False, ""),
    "@dollemore": ("Jesse Dollemore", False, ""),
    "@RebelHQ": ("TYT Network", False, "TYT Network channel"),
    "@StatusCoup": ("Status Coup", False, ""),
    "@SMN": ("Some More News", False, ""),
    "@BelleRanch": ("Belle of the Ranch", False, ""),
    "@harryjsisson": ("Harry Sisson", False, ""),
    "@aaronparnas1": ("Aaron Parnas", False, ""),
    "@rolandsmartin": ("Black Star Network", False, "daily news show"),
    "@DropSiteNews": ("Drop Site", False, ""),
    "@BadFaithPodcast": ("Bad Faith", False, ""),
    "@thejimmydoreshow": ("Jimmy Dore", False, "anti-establishment"),
    "@KimIversen": ("Kim Iversen", False, ""),
    "@NovaraMedia": ("Novara Media", False, "UK"),
    "@lovettorleaveitpodcast": ("Crooked Media", False, "comedy panel"),
    "@PoliticsGirl": ("PoliticsGirl", False, ""),
    "@TheLincolnProject": ("Lincoln Project", False, ""),
    "@chriscuomo": ("Chris Cuomo", False, "NewsNation host, own channel"),
    "@MichaelMaliceofficial": ("Michael Malice", False, ""),
    "@StosselTV": ("John Stossel", False, ""),
    "@RubinReport": ("Rubin Report", False, ""),
    "@ColemanHughesOfficial": ("Coleman Hughes", False, ""),
    "@DarkHorsePod": ("DarkHorse", False, ""),
    "@OfficialFlagrant": ("Flagrant", False, "comedy podcast"),
    "@turningpointusa": ("Turning Point USA", False, ""),
    "@marklevinshow": ("Mark Levin", False, ""),
    "@bbrettcooper": ("Brett Cooper", False, "culture commentary"),
    "@theisabelbrown": ("Isabel Brown", False, "culture commentary"),
    "@lizwheeler": ("Liz Wheeler", False, ""),
    "@AndrewKlavan": ("Daily Wire", False, ""),
    "@RealAlexClark": ("Turning Point USA", False, "Culture Apothecary (TPUSA); wellness / culture"),
    "@BlazeTV": ("Blaze Media", False, ""),
    "@PragerU": ("PragerU", False, "educational format"),
    "@TimcastIRL": ("Timcast", False, ""),
    "@TimcastNews": ("Timcast", False, ""),
    "@AnthonyBrianLogan": ("Anthony Brian Logan", False, ""),
    "@DrSteveTurleyTV": ("Steve Turley", False, ""),
    "@SaltyCracker": ("Salty Cracker", False, "reaction livestreams"),
    "@TheQuartering": ("TheQuartering", False, ""),
    "@ActualJusticeWarrior": ("Actual Justice Warrior", False, ""),
    "@Styxhexenhammer666": ("Styxhexenhammer", False, ""),
    "@dineshdsouza": ("Dinesh D'Souza", False, ""),
    "@RebelNewsOnline": ("Rebel News", False, "Canadian"),
    "@SNEAKO": ("SNEAKO", False, "main channel, 5 uploads"),
    "@LIVESNEAKO": ("SNEAKO", False, ""),
    "@The_Crucible": ("The Crucible", False, "debate streamer"),
    "@JacksonHinkleOfficial": ("Jackson Hinkle", False, "streams + uploads"),
    "@lonerboxlive": ("LonerBox", False, ""),
    "@Xanderhal": ("Xanderhal", False, ""),
    "@DailyDenims": ("Denims", True, "unofficial fan-run channel per description"),
    "@PiscoLitty": ("Pisco", False, "lawyer / debate streamer"),
    "@TheSerfTimes": ("Serf Times", False, "internet-culture commentary"),
    "@FreshFitMiami": ("Fresh & Fit", False, ""),
    "@moreperfectunion": ("More Perfect Union", False, "nonprofit newsroom"),
    "@JackCocchiarellaShow": ("Jack Cocchiarella", False, ""),
    "@TheRealTabithaSpeaks": ("Tabitha Speaks", False, ""),
    "@PhillipScottPodcast": ("Phillip Scott", False, "streams only"),
    "@MrTariqNasheed": ("Tariq Nasheed", False, "FBA"),
    "@underthedesknews": ("Under the Desk News", False, ""),
    "@usefulidiots": ("Useful Idiots", False, ""),
    "@thomhartmann": ("Thom Hartmann", False, ""),
    "@SabbySabs": ("Sabby Sabs", False, ""),
    "@DueDissidence": ("Due Dissidence", False, ""),
    "@thegrayzone7996": ("The Grayzone", False, ""),
    "@GeopoliticalEconomyReport": ("Geopolitical Economy Report", False, "geopolitics analysis"),
    "@DannyHaiphongYT": ("Danny Haiphong", False, "geopolitics streams"),
    "@judgingfreedom": ("Judging Freedom", False, "Napolitano; interviews"),
    "@LeverNews": ("The Lever", False, ""),
    "@DemocracyNow": ("Democracy Now!", False, ""),
    "@doomscrollpodcast": ("Doomscroll", False, ""),
    "@DylanBurnsLIVE": ("Dylan Burns", False, "Ukraine coverage"),
    "@marclamonthillnetwork": ("Marc Lamont Hill", False, ""),
    "@Tim_Black": ("Tim Black", False, ""),
    "@OwenJonesTalks": ("Owen Jones", False, "UK"),
    "@DoubleDownNews": ("Double Down News", False, "UK"),
    "@PoliticsJOE": ("PoliticsJOE", False, "UK"),
    "@TheJoyReidShow": ("Joy Reid", False, ""),
    "@TheDonLemonShow": ("Don Lemon", False, ""),
    "@jimacosta": ("Jim Acosta", False, ""),
    "@msnow": ("MS NOW", False, "formerly MSNBC"),
    "@LegalAFMTN": ("MeidasTouch Network", False, ""),
    "@GlennKirschner2": ("Glenn Kirschner", False, ""),
    "@LegalEagle": ("LegalEagle", False, ""),
    "@DemocracyDocket": ("Democracy Docket", False, ""),
    "@katiephangnews": ("MeidasTouch Network", False, "powered by MeidasTouch per description"),
    "@TheMichaelCohenShow": ("MeidasTouch Network", False, "Mea Culpa / Michael Cohen Show (MeidasTouch network)"),
    "@PTLRadioShow": ("Pushing the Limits", False, "streams"),
    "@thewarningwithsteveschmidt": ("Steve Schmidt", False, ""),
    "@cafedotcom": ("CAFE", False, "Preet Bharara"),
    "@fastpoliticspodcast": ("Fast Politics", False, "interview podcast format"),
    "@RestPoliticsUS": ("The Rest Is Politics US", False, ""),
    "@LastWeekTonight": ("HBO", False, ""),
    "@thehill": ("The Hill", False, "mostly 'Rising' commentary show"),
    "@AfterPartyEmily": ("Emily Jashinsky", False, "formerly Breaking Points"),
    "@wethefifth": ("The Fifth Column", False, ""),
    "@morebridgetphetasy": ("Bridget Phetasy", False, ""),
    "@ZeihanonGeopolitics": ("Peter Zeihan", False, ""),
    "@CaspianReport": ("CaspianReport", False, ""),
    "@PerunAU": ("Perun", False, "defence economics"),
    "@UnHerd": ("UnHerd", False, "UK; interviews"),
    "@ZubyMusic": ("Zuby", False, ""),
    "@winston_marshall": ("Winston Marshall", False, ""),
    "@ClubRandomPodcast": ("Bill Maher", False, ""),
    "@TheAdamCarollaShow1": ("Adam Carolla", False, "comedy"),
    "@NickShirley": ("Nick Shirley", False, "IRL confrontation videos"),
    "@RealDanBongino": ("Dan Bongino", False, ""),
    "@RedactedNews": ("Redacted", False, ""),
    "@GrahamAllen": ("Graham Allen", False, ""),
    "@chicksonright": ("Chicks on the Right", False, ""),
    "@X22Report-y5y": ("X22 Report", False, ""),
    "@AndWeKnowOfficial-o9b": ("And We Know", False, ""),
    "@RSBN": ("RSBN", False, ""),
    "@RealAmericasVoice": ("Real America's Voice", False, ""),
    "@NewsmaxTV": ("Newsmax", False, ""),
    "@oann": ("OAN", False, ""),
    "@HangOutwithSeanHannity": ("Sean Hannity", False, ""),
    "@FoxNews": ("Fox News", False, ""),
    "@FoxNewsChannelClips": ("Fox News", True, "clips channel"),
    "@NBCNews": ("NBC News", False, ""),
    "@CNN": ("CNN", False, ""),
    "@ABCNews": ("ABC News", False, ""),
    "@CBSNews": ("CBS News", False, ""),
    "@NewsNation": ("NewsNation", False, ""),
    "@Reuters": ("Reuters", False, ""),
    "@BBCNews": ("BBC", False, ""),
    "@aljazeeraenglish": ("Al Jazeera", False, ""),
    "@AssociatedPress": ("Associated Press", False, ""),
    "@nytimes": ("New York Times", False, ""),
    "@wsj": ("Wall Street Journal", False, ""),
    "@markets": ("Bloomberg", False, "Bloomberg Television; markets"),
    "@USATODAY": ("USA Today", False, ""),
    "@NPR": ("NPR", False, ""),
    "@POLITICO": ("Politico", False, ""),
    "@axios": ("Axios", False, ""),
    "@Vox": ("Vox", False, ""),
    "@TheDailyBeast": ("Daily Beast", False, ""),
    "@Semafor": ("Semafor", False, ""),
    "@FinancialTimes": ("Financial Times", False, "UK press"),
    "@Forbes": ("Forbes", False, "business"),
    "@TechCrunch": ("TechCrunch", False, "tech"),
    "@TheAtlantic": ("The Atlantic", False, ""),
    "@newyorker": ("The New Yorker", False, ""),
    "@TheEconomist": ("The Economist", False, "UK press"),
    "@nationalreview": ("National Review", False, "magazine"),
    "@nypost": ("New York Post", False, "tabloid"),
    "@clayandbuck": ("Clay & Buck", False, "radio"),
    "@TheBrianKilmeadeShow": ("Fox News", False, "Fox News Radio show"),
    "@MarkDice": ("Mark Dice", False, ""),
    "@PrisonPlanetLive": ("Paul Joseph Watson", False, ""),
    "@LiberalHivemind": ("Liberal Hivemind", False, ""),
    "@MrReaganUSA": ("Mr Reagan", False, "satire series MAGA-MAN"),
    "@BlackConservativePerspective": ("Black Conservative Perspective", False, ""),
    "@FleccasTalks": ("Fleccas Talks", False, ""),
    "@laurenchenclips": ("Lauren Chen", True, "clips channel"),
    "@mikhaila": ("Mikhaila Peterson", False, ""),
    "@MattBernstein1": ("Matt Bernstein", False, "culture commentary"),
    "@TomiLahrenIsFearless": ("Tomi Lahren", False, ""),
    "@RufoandLomez": ("Rufo & Lomez", False, ""),
    "@newdiscourses": ("New Discourses", False, "James Lindsay"),
    "@JesseKellyDC": ("Jesse Kelly", False, ""),
    "@TheAmalaEkpunobi": ("Amala Ekpunobi", False, "culture; formerly PragerU"),
    "@XAVIAER": ("PragerU", False, "'a series from PragerU' per description"),
    "@BlaireWhiteX": ("Blaire White", False, "culture commentary"),
    "@AlexStein99": ("Alex Stein", False, "prank comedian"),
    "@RileyGaines": ("Riley Gaines", False, ""),
    "@SavSays": ("Sav Says", False, ""),
    "@CamHigby": ("Cam Higby", False, "debates"),
    "@BrittanyVenti": ("Brittany Venti", False, "culture commentary"),
    "@jlptalk": ("Jesse Lee Peterson", False, "call-in show"),
    "@AnaEscobarShow": ("Ana Escobar", False, ""),
    "@fightbackpodcast": ("Jake Shields", False, ""),
    "@JustPearlyThings": ("Pearl", False, "gender"),
    "@MyronGainesX": ("Myron Gaines", False, "streams"),
    "@SydneyWatson": ("Sydney Watson", False, "culture commentary"),
    "@ThePodcastoftheLotusEaters": ("Lotus Eaters", False, "UK"),
    "@VivaFrei": ("Viva Frei", False, ""),
    "@RobertGouveiaEsq": ("Robert Gouveia", False, ""),
    "@RekietaLaw": ("Rekieta Law", False, ""),
    "@CashJordan": ("Cash Jordan", False, ""),
    "@ChadPrather1": ("Chad Prather", False, "faith + humour"),
    "@OutKick": ("Fox Corporation", False, "sports & culture (Fox-owned)"),
    "@Shoe0nHead": ("Shoe0nHead", False, ""),
    "@notsoErudite": ("notsoErudite", False, "debate / call-in"),
    "@MikeFromPA": ("Mike from PA", False, "Twitch"),
    "@DestinyDGGClips": ("Destiny", True, "fan channel"),
    "@destinyhqclips": ("Destiny", True, "fan channel"),
    "@TheVaushPit": ("Vaush", True, "second channel, editor-titled"),
    "@HasanReactionsfanTwo": ("HasanAbi", True, "fan channel"),
    "@HasanabiClips": ("HasanAbi", True, "fan channel"),
    "@YaBoiHakim": ("Hakim", False, "explainer videos"),
    "@BadEmpanadaLive": ("BadEmpanada", False, ""),
    "@Lunaoi": ("Luna Oi", False, ""),
    "@revleftradio": ("Rev Left Radio", False, ""),
    "@franifio": ("Bitchuation Room", False, "comedians + organisers"),
    "@BreakThroughNews": ("BreakThrough News", False, ""),
    "@JamarlThomas": ("Jamarl Thomas", False, ""),
    "@NickCruseRBN": ("Revolutionary Blackout Network", False, ""),
    "@Forthepeoplepodcast305": ("Niko House", False, ""),
    "@RonPlacone": ("Ron Placone", False, "comedian"),
    "@katmabu": ("Kat Abughazaleh", False, ""),
    "@evanjmez": ("Evan James", False, ""),
    "@Politicon": ("Politicon", False, ""),
    "@ColeHastings": ("Cole Hastings", False, ""),
    "@ModernDayDebate": ("Modern-Day Debate", False, "debate platform"),
    "@OwenReport": ("Owen Shroyer", False, ""),
    "@JillianMichaels": ("Jillian Michaels", False, ""),
    "@ANINewsIndia": ("ANI", False, "India"),
    "@nousnetwork": ("nous", False, "Indian Muslims research"),
    "@bushrakhanum": ("Network18", False, "Network18 anchor's own channel"),
    "@theGuardian": ("The Guardian", False, "UK press"),
    "@CoreyGilShusterAskProject": ("Ask Project", False, "vox-pop interviews Israel/Palestine"),
    "@ajplus": ("Al Jazeera", False, ""),
    "@Channel5YouTube": ("Channel 5", False, "documentary journalism"),
    "@OfficialSaharTV": ("Sahar TV", False, "religion debates, UK"),
    "@SkyNews": ("Sky News", False, "UK"),
    "@NYTOpinion": ("New York Times", False, ""),
    "@NYTPodcasts": ("New York Times", False, ""),
    "@EzraKleinShow": ("New York Times", False, "NYT Opinion podcast"),
    "@Unpacked": ("Unpacked", False, "Israel-focused explainers"),
    "@timesofindia": ("Times Group", False, "India"),
    "@Firstpost": ("Network18", False, "India"),
    "@60minutes": ("CBS News", False, ""),
    "@chinainsights-r2w": ("China Insights", False, "China news"),
    "@TimesNowWorld": ("Times Group", False, "India"),
    "@johnnyharris": ("Johnny Harris", False, ""),
    # ---- Rumble ----
    "https://rumble.com/c/GGreenwald": ("Glenn Greenwald", False, "System Update"),
    "https://rumble.com/c/russellbrand": ("Russell Brand", False, ""),
    "https://rumble.com/c/BannonsWarRoom": ("War Room", False, ""),
    "https://rumble.com/c/nickjfuentes": ("Nick Fuentes", False, ""),
    "https://rumble.com/c/TheAlexJonesShowLive": ("InfoWars", False, ""),
}
