"""Proposed lane / organisation / clipper assignment for the 274 creators (Stage 0).

This is the *seed* that pipeline_titles.lanes writes to data/titles/analysis/lanes.csv
for hand correction; every between-group comparison reads lanes.csv, never this
file, so corrections only need to be made in the CSV. Assignments were made from
the channel names, channel descriptions and a sample of titles (2026-09-14).

Lanes (the nine asked for, plus four that the corpus needed):
    left_commentary, right_commentary, centrist_heterodox (never-Trump right,
    libertarian, populist-heterodox), us_legacy_tv, right_tv_network (Newsmax, OAN,
    RSBN, Real America's Voice), wire_international, us_press_print_digital (NYT, WSJ,
    Politico, Vox, ... US print/digital newsrooms), independent_digital_news,
    streamer_reaction, interview_podcast, legal_institutional, humour_satire,
    explainer_geopolitics.

Entry: creator -> (lane, organisation, clipper, note). organisation groups sister
channels of one outlet; clipper marks channels whose titles are written by fans or
an editing team rather than the creator.
"""

LANES = {
    # ---- caption-corpus creators ----
    "@AsmonTV": ("streamer_reaction", "Asmongold", True, "run by Daily Dose of Asmongold / CatDany per description; gaming + politics reaction"),
    "@BenShapiro": ("right_commentary", "Daily Wire", False, ""),
    "@ClipsCandaceOwens": ("right_commentary", "Candace Owens", True, "official clips channel"),
    "@HasanAbi": ("streamer_reaction", "HasanAbi", False, ""),
    "@HasanAbiVODs3": ("streamer_reaction", "HasanAbi", True, "official VOD channel; date-stamped titles written by the VOD team"),
    "@LukeBeasley": ("left_commentary", "Luke Beasley", False, ""),
    "@MattWalsh": ("right_commentary", "Daily Wire", False, ""),
    "@MegynKelly": ("right_commentary", "Megyn Kelly", False, "interview-heavy show; titles are news commentary"),
    "@MeidasTouch": ("left_commentary", "MeidasTouch Network", False, "self-described news network; titles are commentary"),
    "@MichaelKnowles": ("right_commentary", "Daily Wire", False, ""),
    "@PBDPodcast": ("interview_podcast", "Valuetainment", False, "right-leaning"),
    "@PartOfTheProblem": ("right_commentary", "Dave Smith", False, "libertarian / anti-war"),
    "@SecularTalk": ("left_commentary", "Kyle Kulinski", False, ""),
    "@StevenCrowder": ("right_commentary", "Louder with Crowder", False, ""),
    "@TheMajorityReport": ("left_commentary", "Majority Report", False, ""),
    "@TheYoungTurks": ("left_commentary", "TYT Network", False, "cross-posts with The Damage Report"),
    "@TimDillonShow": ("humour_satire", "Tim Dillon", False, "comedian podcast"),
    "@Timcast": ("right_commentary", "Timcast", False, ""),
    "@TuckerCarlson": ("interview_podcast", "Tucker Carlson Network", False, "right; mostly long-form interviews"),
    "@Vaush": ("streamer_reaction", "Vaush", False, ""),
    "@adammockler": ("left_commentary", "Adam Mockler", False, ""),
    "@bennyjohnson": ("right_commentary", "Benny Johnson", False, "TPUSA contributor"),
    "@breakingpoints": ("independent_digital_news", "Breaking Points", False, ""),
    "@briantylercohen": ("left_commentary", "Brian Tyler Cohen", False, ""),
    "@deanwithrs": ("streamer_reaction", "Dean Withers", False, "debate streamer, left"),
    "@destiny": ("streamer_reaction", "Destiny", False, ""),
    "@glennbeck": ("right_commentary", "Blaze Media", False, ""),
    "@hutch": ("streamer_reaction", "Hutch", False, ""),
    "@joerogan": ("interview_podcast", "Joe Rogan", False, ""),
    "@podsaveamerica": ("left_commentary", "Crooked Media", False, ""),
    "@ponderingpolitics": ("left_commentary", "Pondering Politics", False, ""),
    "@samharrisorg": ("interview_podcast", "Sam Harris", False, "centrist"),
    "@thedavidpakmanshow": ("left_commentary", "David Pakman", False, ""),
    # ---- YouTube, rest of the list ----
    "@triggerpod": ("interview_podcast", "Triggernometry", False, "heterodox"),
    "@MLChristiansen": ("right_commentary", "Matt Christiansen", False, ""),
    "@TheOfficerTatum": ("right_commentary", "Officer Tatum", False, ""),
    "@therationalnational": ("left_commentary", "Rational National", False, "Canadian"),
    "@SecondThought": ("left_commentary", "Second Thought", False, "socialist explainer videos"),
    "@bulwarkmedia": ("centrist_heterodox", "The Bulwark", False, "never-Trump right"),
    "@LeejaMiller": ("legal_institutional", "Leeja Miller", False, "lawyer explainer, left"),
    "@PiersMorganUncensored": ("interview_podcast", "Piers Morgan", False, "debate / interview show"),
    "@zeteo": ("independent_digital_news", "Zeteo", False, ""),
    "@TheDamageReport": ("left_commentary", "TYT Network", False, "cross-posts with TYT"),
    "@TheHumanistReport": ("left_commentary", "Humanist Report", False, ""),
    "@FarronBalanced": ("left_commentary", "Farron Balanced", False, ""),
    "@dollemore": ("left_commentary", "Jesse Dollemore", False, ""),
    "@RebelHQ": ("left_commentary", "TYT Network", False, "TYT Network channel"),
    "@StatusCoup": ("independent_digital_news", "Status Coup", False, "left"),
    "@SMN": ("humour_satire", "Some More News", False, ""),
    "@BelleRanch": ("left_commentary", "Belle of the Ranch", False, ""),
    "@harryjsisson": ("left_commentary", "Harry Sisson", False, ""),
    "@aaronparnas1": ("left_commentary", "Aaron Parnas", False, ""),
    "@rolandsmartin": ("independent_digital_news", "Black Star Network", False, "daily news show, left"),
    "@DropSiteNews": ("independent_digital_news", "Drop Site", False, ""),
    "@BadFaithPodcast": ("interview_podcast", "Bad Faith", False, "left"),
    "@thejimmydoreshow": ("left_commentary", "Jimmy Dore", False, "populist / anti-establishment"),
    "@KimIversen": ("centrist_heterodox", "Kim Iversen", False, "populist-heterodox"),
    "@NovaraMedia": ("independent_digital_news", "Novara Media", False, "UK left"),
    "@lovettorleaveitpodcast": ("humour_satire", "Crooked Media", False, "comedy panel"),
    "@PoliticsGirl": ("left_commentary", "PoliticsGirl", False, ""),
    "@TheLincolnProject": ("centrist_heterodox", "Lincoln Project", False, "never-Trump right"),
    "@chriscuomo": ("centrist_heterodox", "Chris Cuomo", False, "NewsNation host, own channel"),
    "@MichaelMaliceofficial": ("interview_podcast", "Michael Malice", False, "anarchist"),
    "@StosselTV": ("right_commentary", "John Stossel", False, "libertarian"),
    "@RubinReport": ("right_commentary", "Rubin Report", False, ""),
    "@ColemanHughesOfficial": ("interview_podcast", "Coleman Hughes", False, "centrist"),
    "@DarkHorsePod": ("centrist_heterodox", "DarkHorse", False, ""),
    "@OfficialFlagrant": ("humour_satire", "Flagrant", False, "comedy podcast"),
    "@turningpointusa": ("right_commentary", "Turning Point USA", False, ""),
    "@marklevinshow": ("right_commentary", "Mark Levin", False, ""),
    "@bbrettcooper": ("right_commentary", "Brett Cooper", False, "culture"),
    "@theisabelbrown": ("right_commentary", "Isabel Brown", False, "culture"),
    "@lizwheeler": ("right_commentary", "Liz Wheeler", False, ""),
    "@AndrewKlavan": ("right_commentary", "Daily Wire", False, ""),
    "@RealAlexClark": ("right_commentary", "Turning Point USA", False, "Culture Apothecary (TPUSA); wellness/culture"),
    "@BlazeTV": ("right_commentary", "Blaze Media", False, ""),
    "@PragerU": ("right_commentary", "PragerU", False, "educational format"),
    "@TimcastIRL": ("right_commentary", "Timcast", False, ""),
    "@TimcastNews": ("right_commentary", "Timcast", False, ""),
    "@AnthonyBrianLogan": ("right_commentary", "Anthony Brian Logan", False, ""),
    "@DrSteveTurleyTV": ("right_commentary", "Steve Turley", False, ""),
    "@SaltyCracker": ("streamer_reaction", "Salty Cracker", False, "right; reaction livestreams"),
    "@TheQuartering": ("right_commentary", "TheQuartering", False, ""),
    "@ActualJusticeWarrior": ("right_commentary", "Actual Justice Warrior", False, ""),
    "@Styxhexenhammer666": ("right_commentary", "Styxhexenhammer", False, "libertarian"),
    "@dineshdsouza": ("right_commentary", "Dinesh D'Souza", False, ""),
    "@RebelNewsOnline": ("independent_digital_news", "Rebel News", False, "Canadian, right"),
    "@SNEAKO": ("streamer_reaction", "SNEAKO", False, "main channel, 5 uploads"),
    "@LIVESNEAKO": ("streamer_reaction", "SNEAKO", False, ""),
    "@The_Crucible": ("streamer_reaction", "The Crucible", False, "debate streamer, right"),
    "@JacksonHinkleOfficial": ("right_commentary", "Jackson Hinkle", False, "'MAGA communist'; streams + uploads"),
    "@lonerboxlive": ("streamer_reaction", "LonerBox", False, ""),
    "@Xanderhal": ("streamer_reaction", "Xanderhal", False, "left"),
    "@DailyDenims": ("streamer_reaction", "Denims", True, "unofficial fan-run channel per description"),
    "@PiscoLitty": ("streamer_reaction", "Pisco", False, "lawyer / debate streamer, left"),
    "@TheSerfTimes": ("streamer_reaction", "Serf Times", False, "internet-culture commentary, left"),
    "@FreshFitMiami": ("right_commentary", "Fresh & Fit", False, "manosphere"),
    "@moreperfectunion": ("independent_digital_news", "More Perfect Union", False, "left nonprofit newsroom"),
    "@JackCocchiarellaShow": ("left_commentary", "Jack Cocchiarella", False, ""),
    "@TheRealTabithaSpeaks": ("left_commentary", "Tabitha Speaks", False, ""),
    "@PhillipScottPodcast": ("left_commentary", "Phillip Scott", False, "streams only"),
    "@MrTariqNasheed": ("left_commentary", "Tariq Nasheed", False, "FBA; not classic left"),
    "@underthedesknews": ("independent_digital_news", "Under the Desk News", False, "left"),
    "@usefulidiots": ("interview_podcast", "Useful Idiots", False, "left"),
    "@thomhartmann": ("left_commentary", "Thom Hartmann", False, ""),
    "@SabbySabs": ("left_commentary", "Sabby Sabs", False, ""),
    "@DueDissidence": ("left_commentary", "Due Dissidence", False, ""),
    "@thegrayzone7996": ("independent_digital_news", "The Grayzone", False, ""),
    "@GeopoliticalEconomyReport": ("independent_digital_news", "Geopolitical Economy Report", False, "anti-imperialist analysis"),
    "@DannyHaiphongYT": ("left_commentary", "Danny Haiphong", False, "geopolitics streams"),
    "@judgingfreedom": ("interview_podcast", "Judging Freedom", False, "Napolitano; anti-war interviews"),
    "@LeverNews": ("independent_digital_news", "The Lever", False, ""),
    "@DemocracyNow": ("independent_digital_news", "Democracy Now!", False, ""),
    "@doomscrollpodcast": ("interview_podcast", "Doomscroll", False, "left"),
    "@DylanBurnsLIVE": ("streamer_reaction", "Dylan Burns", False, "left; Ukraine"),
    "@marclamonthillnetwork": ("left_commentary", "Marc Lamont Hill", False, ""),
    "@Tim_Black": ("left_commentary", "Tim Black", False, ""),
    "@OwenJonesTalks": ("left_commentary", "Owen Jones", False, "UK"),
    "@DoubleDownNews": ("independent_digital_news", "Double Down News", False, "UK left"),
    "@PoliticsJOE": ("independent_digital_news", "PoliticsJOE", False, "UK"),
    "@TheJoyReidShow": ("left_commentary", "Joy Reid", False, ""),
    "@TheDonLemonShow": ("left_commentary", "Don Lemon", False, ""),
    "@jimacosta": ("left_commentary", "Jim Acosta", False, ""),
    "@msnow": ("us_legacy_tv", "MS NOW", False, "formerly MSNBC"),
    "@LegalAFMTN": ("legal_institutional", "MeidasTouch Network", False, ""),
    "@GlennKirschner2": ("legal_institutional", "Glenn Kirschner", False, ""),
    "@LegalEagle": ("legal_institutional", "LegalEagle", False, ""),
    "@DemocracyDocket": ("legal_institutional", "Democracy Docket", False, ""),
    "@katiephangnews": ("left_commentary", "MeidasTouch Network", False, "powered by MeidasTouch per description"),
    "@TheMichaelCohenShow": ("left_commentary", "MeidasTouch Network", False, "Mea Culpa / Michael Cohen Show (MeidasTouch network)"),
    "@PTLRadioShow": ("left_commentary", "Pushing the Limits", False, "streams"),
    "@thewarningwithsteveschmidt": ("centrist_heterodox", "Steve Schmidt", False, "never-Trump right"),
    "@cafedotcom": ("legal_institutional", "CAFE", False, "Preet Bharara"),
    "@fastpoliticspodcast": ("left_commentary", "Fast Politics", False, "interview podcast format"),
    "@RestPoliticsUS": ("centrist_heterodox", "The Rest Is Politics US", False, ""),
    "@LastWeekTonight": ("humour_satire", "HBO", False, ""),
    "@thehill": ("us_press_print_digital", "The Hill", False, "mostly 'Rising' commentary show"),
    "@AfterPartyEmily": ("right_commentary", "Emily Jashinsky", False, "right-populist; formerly Breaking Points"),
    "@wethefifth": ("centrist_heterodox", "The Fifth Column", False, "libertarian"),
    "@morebridgetphetasy": ("interview_podcast", "Bridget Phetasy", False, ""),
    "@ZeihanonGeopolitics": ("explainer_geopolitics", "Peter Zeihan", False, ""),
    "@CaspianReport": ("explainer_geopolitics", "CaspianReport", False, ""),
    "@PerunAU": ("explainer_geopolitics", "Perun", False, "defence economics"),
    "@UnHerd": ("centrist_heterodox", "UnHerd", False, "UK; interviews"),
    "@ZubyMusic": ("interview_podcast", "Zuby", False, "right-leaning"),
    "@winston_marshall": ("interview_podcast", "Winston Marshall", False, "right-leaning"),
    "@ClubRandomPodcast": ("interview_podcast", "Bill Maher", False, ""),
    "@TheAdamCarollaShow1": ("interview_podcast", "Adam Carolla", False, "comedy; right-leaning"),
    "@NickShirley": ("right_commentary", "Nick Shirley", False, "IRL confrontation videos"),
    "@RealDanBongino": ("right_commentary", "Dan Bongino", False, ""),
    "@RedactedNews": ("independent_digital_news", "Redacted", False, "populist; right-leaning"),
    "@GrahamAllen": ("right_commentary", "Graham Allen", False, ""),
    "@chicksonright": ("right_commentary", "Chicks on the Right", False, ""),
    "@X22Report-y5y": ("right_commentary", "X22 Report", False, "conspiracy"),
    "@AndWeKnowOfficial-o9b": ("right_commentary", "And We Know", False, "conspiracy"),
    "@RSBN": ("right_tv_network", "RSBN", False, ""),
    "@RealAmericasVoice": ("right_tv_network", "Real America's Voice", False, ""),
    "@NewsmaxTV": ("right_tv_network", "Newsmax", False, ""),
    "@oann": ("right_tv_network", "OAN", False, ""),
    "@HangOutwithSeanHannity": ("interview_podcast", "Sean Hannity", False, "right"),
    "@FoxNews": ("us_legacy_tv", "Fox News", False, ""),
    "@FoxNewsChannelClips": ("us_legacy_tv", "Fox News", True, "clips channel"),
    "@NBCNews": ("us_legacy_tv", "NBC News", False, ""),
    "@CNN": ("us_legacy_tv", "CNN", False, ""),
    "@ABCNews": ("us_legacy_tv", "ABC News", False, ""),
    "@CBSNews": ("us_legacy_tv", "CBS News", False, ""),
    "@NewsNation": ("us_legacy_tv", "NewsNation", False, ""),
    "@Reuters": ("wire_international", "Reuters", False, ""),
    "@BBCNews": ("wire_international", "BBC", False, ""),
    "@aljazeeraenglish": ("wire_international", "Al Jazeera", False, ""),
    "@AssociatedPress": ("wire_international", "Associated Press", False, ""),
    "@nytimes": ("us_press_print_digital", "New York Times", False, ""),
    "@wsj": ("us_press_print_digital", "Wall Street Journal", False, ""),
    "@markets": ("us_press_print_digital", "Bloomberg", False, "Bloomberg Television; markets"),
    "@USATODAY": ("us_press_print_digital", "USA Today", False, ""),
    "@NPR": ("us_press_print_digital", "NPR", False, ""),
    "@POLITICO": ("us_press_print_digital", "Politico", False, ""),
    "@axios": ("us_press_print_digital", "Axios", False, ""),
    "@Vox": ("us_press_print_digital", "Vox", False, ""),
    "@TheDailyBeast": ("us_press_print_digital", "Daily Beast", False, ""),
    "@Semafor": ("us_press_print_digital", "Semafor", False, ""),
    "@FinancialTimes": ("wire_international", "Financial Times", False, "UK press"),
    "@Forbes": ("us_press_print_digital", "Forbes", False, "business"),
    "@TechCrunch": ("us_press_print_digital", "TechCrunch", False, "tech"),
    "@TheAtlantic": ("us_press_print_digital", "The Atlantic", False, ""),
    "@newyorker": ("us_press_print_digital", "The New Yorker", False, ""),
    "@TheEconomist": ("wire_international", "The Economist", False, "UK press"),
    "@nationalreview": ("us_press_print_digital", "National Review", False, "right magazine"),
    "@nypost": ("us_press_print_digital", "New York Post", False, "tabloid"),
    "@clayandbuck": ("right_commentary", "Clay & Buck", False, "radio"),
    "@TheBrianKilmeadeShow": ("right_commentary", "Fox News", False, "Fox News Radio show"),
    "@MarkDice": ("right_commentary", "Mark Dice", False, ""),
    "@PrisonPlanetLive": ("right_commentary", "Paul Joseph Watson", False, ""),
    "@LiberalHivemind": ("right_commentary", "Liberal Hivemind", False, ""),
    "@MrReaganUSA": ("right_commentary", "Mr Reagan", False, "satire series MAGA-MAN"),
    "@BlackConservativePerspective": ("right_commentary", "Black Conservative Perspective", False, ""),
    "@FleccasTalks": ("right_commentary", "Fleccas Talks", False, ""),
    "@laurenchenclips": ("right_commentary", "Lauren Chen", True, "clips channel"),
    "@mikhaila": ("interview_podcast", "Mikhaila Peterson", False, ""),
    "@MattBernstein1": ("left_commentary", "Matt Bernstein", False, "culture"),
    "@TomiLahrenIsFearless": ("right_commentary", "Tomi Lahren", False, ""),
    "@RufoandLomez": ("right_commentary", "Rufo & Lomez", False, ""),
    "@newdiscourses": ("right_commentary", "New Discourses", False, "James Lindsay"),
    "@JesseKellyDC": ("right_commentary", "Jesse Kelly", False, ""),
    "@TheAmalaEkpunobi": ("right_commentary", "Amala Ekpunobi", False, "culture; formerly PragerU"),
    "@XAVIAER": ("right_commentary", "PragerU", False, "'a series from PragerU' per description"),
    "@BlaireWhiteX": ("right_commentary", "Blaire White", False, "culture"),
    "@AlexStein99": ("humour_satire", "Alex Stein", False, "prank comedian, right"),
    "@RileyGaines": ("right_commentary", "Riley Gaines", False, ""),
    "@SavSays": ("right_commentary", "Sav Says", False, ""),
    "@CamHigby": ("right_commentary", "Cam Higby", False, "debates"),
    "@BrittanyVenti": ("right_commentary", "Brittany Venti", False, "culture"),
    "@jlptalk": ("right_commentary", "Jesse Lee Peterson", False, "call-in show"),
    "@AnaEscobarShow": ("right_commentary", "Ana Escobar", False, ""),
    "@fightbackpodcast": ("right_commentary", "Jake Shields", False, "anti-Zionist right"),
    "@JustPearlyThings": ("right_commentary", "Pearl", False, "manosphere / gender"),
    "@MyronGainesX": ("right_commentary", "Myron Gaines", False, "streams"),
    "@SydneyWatson": ("right_commentary", "Sydney Watson", False, "culture"),
    "@ThePodcastoftheLotusEaters": ("right_commentary", "Lotus Eaters", False, "UK"),
    "@VivaFrei": ("legal_institutional", "Viva Frei", False, "right"),
    "@RobertGouveiaEsq": ("legal_institutional", "Robert Gouveia", False, "right"),
    "@RekietaLaw": ("legal_institutional", "Rekieta Law", False, ""),
    "@CashJordan": ("right_commentary", "Cash Jordan", False, ""),
    "@ChadPrather1": ("right_commentary", "Chad Prather", False, "faith + humour"),
    "@OutKick": ("right_commentary", "Fox Corporation", False, "sports & culture (Fox-owned)"),
    "@Shoe0nHead": ("centrist_heterodox", "Shoe0nHead", False, "anti-woke left"),
    "@notsoErudite": ("streamer_reaction", "notsoErudite", False, "debate / call-in"),
    "@MikeFromPA": ("streamer_reaction", "Mike from PA", False, "left; Twitch"),
    "@DestinyDGGClips": ("streamer_reaction", "Destiny", True, "fan channel"),
    "@destinyhqclips": ("streamer_reaction", "Destiny", True, "fan channel"),
    "@TheVaushPit": ("streamer_reaction", "Vaush", True, "second channel, editor-titled"),
    "@HasanReactionsfanTwo": ("streamer_reaction", "HasanAbi", True, "fan channel"),
    "@HasanabiClips": ("streamer_reaction", "HasanAbi", True, "fan channel"),
    "@YaBoiHakim": ("left_commentary", "Hakim", False, "Marxist explainer"),
    "@BadEmpanadaLive": ("streamer_reaction", "BadEmpanada", False, ""),
    "@Lunaoi": ("left_commentary", "Luna Oi", False, ""),
    "@revleftradio": ("interview_podcast", "Rev Left Radio", False, "left"),
    "@franifio": ("humour_satire", "Bitchuation Room", False, "comedians + organisers"),
    "@BreakThroughNews": ("independent_digital_news", "BreakThrough News", False, "left"),
    "@JamarlThomas": ("left_commentary", "Jamarl Thomas", False, ""),
    "@NickCruseRBN": ("left_commentary", "Revolutionary Blackout Network", False, ""),
    "@Forthepeoplepodcast305": ("left_commentary", "Niko House", False, ""),
    "@RonPlacone": ("humour_satire", "Ron Placone", False, "comedian"),
    "@katmabu": ("left_commentary", "Kat Abughazaleh", False, ""),
    "@evanjmez": ("left_commentary", "Evan James", False, ""),
    "@Politicon": ("interview_podcast", "Politicon", False, ""),
    "@ColeHastings": ("centrist_heterodox", "Cole Hastings", False, ""),
    "@ModernDayDebate": ("streamer_reaction", "Modern-Day Debate", False, "debate platform"),
    "@OwenReport": ("right_commentary", "Owen Shroyer", False, ""),
    "@JillianMichaels": ("interview_podcast", "Jillian Michaels", False, "right-leaning"),
    "@ANINewsIndia": ("wire_international", "ANI", False, "India"),
    "@nousnetwork": ("explainer_geopolitics", "nous", False, "Indian Muslims research"),
    "@bushrakhanum": ("wire_international", "Network18", False, "Network18 anchor's own channel"),
    "@theGuardian": ("wire_international", "The Guardian", False, "UK press"),
    "@CoreyGilShusterAskProject": ("explainer_geopolitics", "Ask Project", False, "vox-pop interviews Israel/Palestine"),
    "@ajplus": ("wire_international", "Al Jazeera", False, ""),
    "@Channel5YouTube": ("independent_digital_news", "Channel 5", False, "documentary journalism"),
    "@OfficialSaharTV": ("right_commentary", "Sahar TV", False, "religion debates, UK"),
    "@SkyNews": ("wire_international", "Sky News", False, "UK"),
    "@NYTOpinion": ("us_press_print_digital", "New York Times", False, ""),
    "@NYTPodcasts": ("us_press_print_digital", "New York Times", False, ""),
    "@EzraKleinShow": ("interview_podcast", "New York Times", False, "NYT Opinion podcast"),
    "@Unpacked": ("explainer_geopolitics", "Unpacked", False, "Israel-focused explainers"),
    "@timesofindia": ("wire_international", "Times Group", False, "India"),
    "@Firstpost": ("wire_international", "Network18", False, "India"),
    "@60minutes": ("us_legacy_tv", "CBS News", False, ""),
    "@chinainsights-r2w": ("independent_digital_news", "China Insights", False, "anti-CCP China news"),
    "@TimesNowWorld": ("wire_international", "Times Group", False, "India"),
    "@johnnyharris": ("explainer_geopolitics", "Johnny Harris", False, ""),
    # ---- Rumble ----
    "https://rumble.com/c/GGreenwald": ("independent_digital_news", "Glenn Greenwald", False, "System Update; heterodox"),
    "https://rumble.com/c/russellbrand": ("centrist_heterodox", "Russell Brand", False, ""),
    "https://rumble.com/c/BannonsWarRoom": ("right_commentary", "War Room", False, ""),
    "https://rumble.com/c/nickjfuentes": ("right_commentary", "Nick Fuentes", False, ""),
    "https://rumble.com/c/TheAlexJonesShowLive": ("right_commentary", "InfoWars", False, ""),
}
